version: "3"

# volumes:
#   db:
#   logs:

services:
  db:
    image: postgres:14
    restart: always
    env_file:
      - backend/app/.env
    env_file:
      - .env
    # volumes:
    #   - "db:/var/lib/postgresql/data"
    ports:
      - "5555:5432"
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 10s
      timeout: 3s
      retries: 3

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    # volumes:
    #   - "logs:/data"
    ports:
      - "3333:3333"
    depends_on:
      - db

  worker:
    image: 0xb1b1/hse_mts_hack_worker:latest
    restart: always
    build:
      context: ./worker
      dockerfile: docker/Dockerfile
    env_file:
      - .env
    ports:
      - 8000:8000
    depends_on:
      - db
