---
apiVersion: v1
kind: Service
metadata:
  name: worker-lb
  namespace: deepmisis-hse
spec:
  type: LoadBalancer
  selector:
    app: dm-worker
  ports:
    - name: http
      protocol: TCP
      port: 29600
      targetPort: 8000
