---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: deepmisis-hse
spec:
  type: ClusterIP
  selector:
    app: dm-api
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
