---
apiVersion: v1
kind: Service
metadata:
  name: coordinator
  namespace: deepmisis-hse
spec:
  type: ClusterIP
  selector:
    app: dm-coordinator
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
