---
# Source: telewatcher/charts/telewatcher-worker/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: telewatcher-worker
  labels:
    helm.sh/chart: telewatcher-worker-0.1.0
    app.kubernetes.io/name: telewatcher-worker
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: telewatcher-worker
    app.kubernetes.io/instance: release-name
