version: '3.9'

# volumes:
#   db:
#     driver: local

services:
  coordinator:
    image: 0xb1b1/hse_mts_hack_coordinator:latest
    restart: always
    build:
      context: ../
      dockerfile: docker/Dockerfile
    env_file:
      - ../.env
    ports:
      - 8001:8001
    depends_on:
      - db

  db:
    image: postgres:14
    restart: always
    env_file:
      - ../.env
    ports:
      - 5432:5432
    # volumes:
    #   - "db:/var/lib/postgresql/data"
